services:
  kiwix:
    image: ghcr.io/kiwix/kiwix-serve
    container_name: kiwix-wikipedia
    volumes:
      - ./data:/data:z # :z is required on SELinux systems
    command:
      - "*.zim"
    ports:
      - "8080:8080"
    restart: unless-stopped
